### ISSUE TITLE
List of Rubies has an error

### ISSUE THREAD

**Issue by thoran** [ruby/actions#15]
As per https://bugs.ruby-lang.org/issues/18584 where I initially reported this...

The name for this entry on https://cache.ruby-lang.org/pub/ruby/index.txt is wrong:

ruby-1.8.7-preview4.tar https://cache.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-preview4.tar.zip a172645d4d4ba50aa5d68dc891742bf254253ded 27cf4c38c2ff9ae6045f7eefcf5164a30a69b1042af64cf729dc180363e629f8 ee67b089774cbf25e667195614e0ee363b0f5cf83aae6fe0fe3fb654ee3dd42eac7c0b436da7069f5b1df1b67c331855f0d787ed5b9c78d18b2bb731286979cc

It should be (sans ".tar"):

ruby-1.8.7-preview4 https://cache.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-preview4.tar.zip a172645d4d4ba50aa5d68dc891742bf254253ded 27cf4c38c2ff9ae6045f7eefcf5164a30a69b1042af64cf729dc180363e629f8 ee67b089774cbf25e667195614e0ee363b0f5cf83aae6fe0fe3fb654ee3dd42eac7c0b436da7069f5b1df1b67c331855f0d787ed5b9c78d18b2bb731286979cc

I discovered this whilst parsing the page for automating keeping Rubies updated.

**Comment by znz** [comment]
I think `index.txt` is correct.
I think it exists due to a mistake at the time of release.

**Comment by thoran** [comment]
I've taken another look at this and you are correct that the index accurately reflects the contents of the bucket.

Note that the offending file is the same as what I presume is the correctly named '.zip' file:

... 5897462 Oct 16 22:16 ruby-1.8.7-preview4.tar.zip
... 5897462 Oct 16 22:17 ruby-1.8.7-preview4.zip

Note also that all versions of Ruby immediately prior and following have 3 entries per version: `.tar.bz2', '.tar.gz', and '.zip', whereas `ruby-1.8.7-preview4` has 4.

There are no other entries in the entire index which have the extension `.tar.zip`.

From where I sit, the fourth, extra, additional, unnecessary entry for ruby-1.8.7-preview4 can safely be deleted from the bucket.

**Comment by hsbt** [comment]
@thoran Thanks for reporting. I removed `ruby-1.8.7-preview4.tar.zip@` from our distribution buckets. In the next time, `index.txt` will be fixed.
